AWSTemplateFormatVersion: 2010-09-09
Description: Script to create a ecs repository

Metadata: 

  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label: 
          default: Repository Configuration
        Parameters:
          - RepositoryName
      
    ParameterLabels:
      RepositoryName:
        default: Repository Name

Parameters:

  RepositoryName:
    Type: String
    Default: ch-dev-user-api-repository
    Description: Enter a repository name.
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Repository name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).

Resources:

  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName:
        Ref: RepositoryName
