AWSTemplateFormatVersion: 2010-09-09
Description: Script to create a ECS cluster

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: ECS Cluster Configuration
        Parameters:
            - ECSClusterName
            - ECSClusterEnvironment
          
    ParameterLabels:
      ECSClusterName:
        default: Cluster Name
      ECSClusterEnvironment:
        default: Cluster Environment

Parameters:

  ECSClusterName:
    Type: String
    Default: user-reviews
    Description: Enter a cluster name.
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Cluster name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).

  ECSClusterEnvironment:
    Type: String
    Default: testing
    Description: Enter a cluster environment.
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Cluster environment can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).

Resources:

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName:
        Ref: ECSClusterName
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
      Tags:
        - Key: environment
          Value:
            Ref: ECSClusterEnvironment