name: user-reviews-deployment

services:
  user-reviews:
    image: sjala/user-reviews:1.4
    depends_on:
       - mysql
    expose:
      - "8080"
    working_dir: /usr/app
    volumes:
      - ./:/app
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_CONFIG_DIR: ${APP_CONFIG_DIR}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql-data:/usr/app
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
       - "33061:33061"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-reviews
    ports:
      - "80:80"
volumes:
  mysql-data:
    external: false
networks:
  default:
    driver: bridge
    name: user-reviews

